/* Presentation only: original names remain the stable save/lookup identifiers. */
const CULTIVATION_DISPLAY_NAMES = Object.freeze({
    "Homeless": "Open Sky", "Tent": "Traveler's Tent", "Wooden Hut": "Cultivator's Hut",
    "Cottage": "Mountain Cottage", "House": "Courtyard House", "Large House": "Cultivation Estate",
    "Small Palace": "Sect Pavilion", "Grand Palace": "Sect Palace", "Town Ruler": "Town Protector",
    "City Ruler": "City Guardian", "Nation Ruler": "Dynasty Sovereign", "Pocket Dimension": "Pocket Dimension",
    "Void Realm": "Void Realm", "Void Universe": "Void Universe", "Astral Realm": "Astral Realm",
    "Galactic Throne": "Celestial Throne", "Spaceship": "Flying Palace", "Planet": "Spirit World",
    "Ringworld": "Heavenly Ring", "Stellar Neighborhood": "Constellation Domain", "Galaxy": "Star Domain",
    "Supercluster": "Celestial Expanse", "Galaxy Filament": "Heavenly Meridian",
    "Observable Universe": "Boundless Heavens", "Multiverse": "Myriad Worlds",
    "Quantum World": "Primordial Realm", "Boötes Void": "Great Emptiness",
    "Beggar": "Wandering Beggar", "Farmer": "Herb Farmer", "Fisherman": "River Gatherer",
    "Miner": "Spirit Ore Miner", "Blacksmith": "Artifact Smith", "Merchant": "Traveling Merchant",
    "Book": "Study Manual", "Dumbbells": "Tempering Weights", "Personal Squire": "Personal Retainer",
    "Steel Longsword": "Steel Spirit Sword", "Butler": "Household Steward", "Study Desk": "Scholar's Desk",
    "Library": "Scripture Library", "Observatory": "Star Pavilion",
    "Squire": "Outer Sect Guard",
    "Footman": "Sect Sentinel",
    "Veteran footman": "Veteran Sentinel",
    "Centenary": "Patrol Captain",
    "Knight": "Sword Disciple",
    "Veteran Knight": "Sword Adept",
    "Holy Knight": "Spiritblade Guardian",
    "Lieutenant General": "Martial Elder",
    "Student": "Scripture Student",
    "Apprentice Mage": "Talisman Apprentice",
    "Adept Mage": "Spirit Arts Adept",
    "Master Wizard": "Formation Master",
    "Archmage": "Spirit Arts Elder",
    "Chronomancer": "Time Dao Sage",
    "Chairman": "Spirit Hall Master",
    "Imperator": "Sect Patriarch",
    "Corrupted": "Void Initiate",
    "Void Slave": "Void Acolyte",
    "Void Fiend": "Void Disciple",
    "Abyss Anomaly": "Abyss Adept",
    "Void Wraith": "Void Soul",
    "Void Reaver": "Void Walker",
    "Void Lord": "Void Sovereign",
    "Abyss God": "Abyss Ancestor",
    "Eternal Wanderer": "Wandering Immortal",
    "Nova": "Star Forger",
    "Sigma Proioxis": "Heavenly Lawkeeper",
    "Acallaris": "Primordial Ancestor",
    "One Above All": "Dao Progenitor",
    "Snow Crash": "Heavenly Gatekeeper",
    "Player One": "Cycle Warden",
    "Lost in the dark": "Eternal Seeker",
    "Omega": "Origin Sovereign",
    "Concentration": "Focused Mind",
    "Productivity": "Diligent Practice",
    "Bargaining": "Merchant's Insight",
    "Meditation": "Serene Meditation",
    "Strength": "Body Tempering",
    "Battle Tactics": "Battle Formations",
    "Muscle Memory": "Marrow Refinement",
    "Mana Control": "Meridian Control",
    "Life Essence": "Longevity Scripture",
    "Time Warping": "Time Dilation",
    "Astral Body": "Spirit Body",
    "Temporal Dimension": "Secluded Time Realm",
    "All Seeing Eye": "Heavenly Sight",
    "Brainwashing": "Soul Persuasion",
    "Abyssal Qi Condensation": "Abyssal Qi Condensation",
    "Heart Demon Suppression": "Heart Demon Suppression",
    "Dark Influence": "Demonic Resonance",
    "Evil Control": "Demonic Refinement",
    "Intimidation": "Demonic Pressure",
    "Demon Training": "Demonic Tempering",
    "Blood Meditation": "Blood Essence Meditation",
    "Demon's Wealth": "Demonic Prosperity",
    "Dark Knowledge": "Forbidden Scriptures",
    "Void Influence": "Void Resonance",
    "Time Loop": "Temporal Circulation",
    "Evil Incarnate": "Demonic Incarnation",
    "Absolute Wish": "Heavenly Will",
    "Void Amplification": "Void Attunement",
    "Mind Release": "Unbound Mind",
    "Ceaseless Abyss": "Endless Vitality",
    "Void Symbiosis": "Void Communion",
    "Void Embodiment": "Void Incarnation",
    "Abyss Manipulation": "Abyss Command",
    "Cosmic Longevity": "Eternal Life Scripture",
    "Cosmic Recollection": "Past-Life Recollection",
    "Essence Collector": "Dao Comprehension",
    "Galactic Command": "Celestial Authority",
    "Yin Yang": "Yin Yang",
    "Parallel Universe": "Myriad Self Cultivation",
    "Higher Dimensions": "Higher Heaven Body",
    "Epiphany": "Sudden Enlightenment",
    "Dark Prince": "Soul Inheritance",
    "Dark Ruler": "Inner World Sovereignty",
    "Immortal Ruler": "Immortal Authority",
    "Dark Magician": "Dao Insight",
    "Universal Ruler": "Heavenly Arts Mastery",
    "Blinded By Darkness": "Boundless Understanding",
    "Sapphire Charm": "Jade Meridian Charm",
    "Mind's Eye": "Insight Jade",
    "Void Necklace": "Void Pendant",
    "Void Armor": "Void Vestment",
    "Void Blade": "Void Spirit Blade",
    "Void Orb": "Void Pearl",
    "Void Dust": "Void Sand",
    "Celestial Robe": "Celestial Robe",
    "Universe Fragment": "Heaven Fragment",
    "Multiverse Fragment": "Myriad Worlds Fragment",
    "Stairway to heaven": "Stairway to Immortality",
    "Highway to hell": "Demonic Altar",
    "Tesseract": "World Formation Seal",
    "Desintegration": "World Refining Cauldron",
    "Custom Galaxy": "Personal Star Realm",
    "Hypersphere": "Heaven-Encompassing Formation",
    "Magic Eye": "Awakened Soul Seal",
    "Almighty Eye": "Perfected Soul Seal",
    "Deal with the Devil": "Demonic Covenant",
    "Transcendent Master": "Dao Ascendant",
    "Eternal Time": "Eternal Time",
    "Hell Portal": "Demonic Gate",
    "Inferno": "Demonic Furnace",
    "God's Blessings": "Heaven's Favor",
    "Faint Hope": "First Insight",
    "New Beginning": "Immortal Awakening",
    "Rise of Great Heroes": "Rise of the Immortals",
    "Lazy Heroes": "Tranquil Immortals",
    "Dirty Heroes": "Earthbound Immortals",
    "Angry Heroes": "Resolute Immortals",
    "Tired Heroes": "Tireless Immortals",
    "Scared Heroes": "Fearless Immortals",
    "Good Heroes": "Virtuous Immortals",
    "Funny Heroes": "Carefree Immortals",
    "Beautiful Heroes": "Radiant Immortals",
    "Awesome Heroes": "Exalted Immortals",
    "Furious Heroes": "Unyielding Immortals",
    "Superb Heroes": "Peerless Immortals",
    "A new beginning": "World Seed Awakening",
    "Mind Control": "Demonic Communion",
    "Galactic Emperor": "Celestial Patriarch",
    "Dark Matter Harvester": "World Essence Harvest",
    "A Dark Era": "Inner World Era",
    "Dark Orbiter": "World Pearl Formation",
    "Dark Matter Mining": "World Vein Extraction",
    "The new gold": "Dao Abundance",
    "The Devil inside you": "Inner Demon",
    "Strange Magic": "Hidden Heavenly Arts",
    "Speed speed speed": "Flow of Eternity",
    "Life is valueable": "Precious Lifespan",
    "Dark Matter Millionaire": "Boundless World Essence",
    "The new Dark Matter": "Heavenly Cycle Awakening",
    "Strong Hope": "Deepening Insight",
    "Ruler of the Metaverse": "Lord of Heavenly Cycles",
    "A New Hope": "Perfect Insight",
    "Time is a flat circle": "Wheel of Reincarnation",
    "The End is near": "Beyond the Heavens",
    "The End": "Return to the Origin",
    "Common work": "Mortal Livelihoods",
    "Military": "Martial Hall",
    "The Arcane Association": "Spirit Arts Hall",
    "The Void": "Void Path",
    "Galactic Council": "Celestial Court",
    "Metaverse Guards": "Heavenly Wardens",
    "Fundamentals": "Foundational Techniques",
    "Combat": "Martial Techniques",
    "Magic": "Spirit Arts",
    "Dark Magic": "Demonic Arts",
    "Void Manipulation": "Void Techniques",
    "Celestial Powers": "Celestial Techniques",
    "Almightiness": "Dao Techniques",
    "Darkness": "Origin Techniques",
    "Properties": "Dwellings",
    "Misc": "Treasures & Retainers",
});
function displayName(name) {
    return CULTIVATION_DISPLAY_NAMES[name] || name;
}

/* Visible-text projection only: identifiers, handlers and save data are not translated. */
const CULTIVATION_TERMS = Object.freeze({
    "The rich and the poor": "Trial of Poverty",
    "Dark Orb Generator": "World Pearl Formation",
    "A miracle": "Ancestral Blessing",
    "A deal with the Chairman": "Patriarch Covenant",
    "A gift from God": "Heaven's Gift",
    "Gotta be fast": "Flowing Time",
    "Life coach": "Lineage Mentor",
    "Speed is life": "Dao of Swiftness",
    "Your greatest debt": "Karmic Debt",
    "Explosion of the universe": "Opening the Heavens",
    "Multiverse explorer": "Myriad Worlds Pilgrimage",
    "Eye Age Requirement": "Reincarnation Age Requirement",
    "Evil Age Requirement": "Demonic Awakening Age Requirement",
    "Dark Matter shop upgrades": "Inner World Treasury upgrades",
    "2x perk points gain": "2x Heavenly Merit gain",
    "10x perk points gain": "10x Heavenly Merit gain",
    "Reincarnate (Touch the eye)":"Reincarnate", "Touch the eye":"Reincarnate", "touching the eyeball":"activating the soul seal",
    "Embrace evil":"Embrace the Demonic Path", "Collapse the universe":"Form an Inner World", "Go to Metaverse":"Enter the Heavenly Cycle",
    "Transcend":"Ascend the Dao", "Evil perks":"Demonic Talents", "Evil perk points":"Demonic Talent Points", "EPP":"DTP",
    "Dark Matter shop":"Inner World Treasury", "dark shop":"World Treasury", "Dark Matter abilities":"World Arts",
    "Dark Matter Skills":"World Arts", "Dark Orbs":"World Pearls", "dark orb":"world pearl", "Dark Matter":"World Essence",
    "Metaverse perk points":"Heavenly Merit", "perk points":"Merit Points", "Metaverse":"Heavenly Cycle",
    "Hypercubes":"World Seals", "Hypercube":"World Seal", "Essence":"Dao Essence", "Evil":"Demonic Energy",
    "Great Hero & Skill XP":"Immortal Duty & Technique XP", "Great heroes":"Immortal cultivators", "Great Hero":"Immortal Duty",
    "Hero XP":"Duty XP", "Hero Pay":"Duty Income", "Heroic":"Immortal", "Heroes":"Cultivators", "Hero":"Cultivator",
    "Skill XP":"Technique XP", "Skills":"Techniques", "Skill":"Technique", "Jobs":"Duties", "Job":"Duty",
    "Happiness":"Inner Harmony", "Amulet":"Soul Jade", "living eyeball":"awakened soul seal", "eyeball":"soul seal",
    "T.A.A.":"Spirit Arts Hall", "T.A.A":"Spirit Arts Hall", "Arcane Association":"Spirit Arts Hall",
    "An unhappy life":"Trial of Stillness", "Rich and the poor":"Trial of Poverty", "Time does not fly":"Trial of Frozen Time",
    "Dance with the devil":"Trial of the Inner Demon", "Legends never die":"Trial of Mortal Limits", "The darkest time":"Trial of the Empty World",
    "Challenges":"Tribulations", "Challenge":"Tribulation", "Milestones":"Dao Insights", "Milestone":"Dao Insight",
    "Shop":"Treasury", "Sacrifices":"Offerings", "Sacrifice":"Offering", "Perks":"Talents", "Perk":"Talent",
    "Great":"Immortal", "mana":"spiritual energy", "mages":"spirit adepts", "mage":"spirit adept",
    "wizardry":"spirit arts", "wizard":"spirit master", "spells":"techniques", "spell":"technique",
    "knights":"sword disciples", "knight":"sword disciple", "footmen":"sentinels", "soldiers":"sect guards",
    "the Devil":"the Demon Sovereign", "devil":"demon sovereign", "Hell":"the Nether Realm", "God":"Heaven",
    "universe":"heaven", "universes":"heavens", "planets":"spirit worlds", "galactic":"celestial"
});
let cultivationTextMatcher;
let cultivationTextLookup;
let cultivationProtectedTerms;
function cultivationText(value) {
    const text = String(value ?? "");
    if (!cultivationTextMatcher) {
        const entries = [...Object.entries(CULTIVATION_TERMS), ...Object.entries(CULTIVATION_DISPLAY_NAMES)];
        cultivationTextLookup = new Map(entries.map(([key, value]) => [key.toLowerCase(), value]));
        cultivationProtectedTerms = new Set(entries.map(([,value]) => value.toLowerCase()));
        const phrases = [...new Set([...entries.map(([key])=>key), ...entries.map(([,value])=>value)])];
        const escape = text => text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        cultivationTextMatcher = new RegExp("(?<![\\p{L}\\p{N}_])(?:" + phrases.sort((a,b)=>b.length-a.length).map(escape).join("|") + ")(?![\\p{L}\\p{N}_])", "giu");
    }
    return text.replace(cultivationTextMatcher, match => cultivationProtectedTerms.has(match.toLowerCase())
        ? match : cultivationTextLookup.get(match.toLowerCase()) || match);
}

const CULTIVATION_TOOLTIP_OVERRIDES = {
    "Abyssal Qi Condensation": "Draw Qi through demonic meridians. Each normal level adds 1% to a separate cultivation-speed multiplier, without changing Inner Harmony. Unlocks at 100k Demonic Energy.",
    "Heart Demon Suppression": "Subdue your inner demons. Breakthrough Stability divides the failure risk caused by Demonic Energy. Unlocks at 100 Demonic Energy.",
    "Homeless": "Rest beneath the open sky. Your journey begins with no dwelling upkeep.",
    "Tent": "A simple shelter beside the mountain road offers a little peace for daily practice.",
    "Wooden Hut": "A secluded hut gives you a quiet place to study and gather your thoughts.",
    "Cottage": "A mountain cottage provides steady comfort away from the noise of the market.",
    "House": "A private courtyard surrounds your study and meditation rooms.",
    "Large House": "An estate with gardens and practice halls supports a comfortable cultivation life.",
    "Small Palace": "A fine sect pavilion surrounds your daily practice with comfort and care.",
    "Grand Palace": "A splendid palace offers the comforts of a great sect, with considerable upkeep.",
    "Town Ruler": "Maintain a protected town whose residences and services support your life.",
    "City Ruler": "A city-sized domain provides abundant comforts, with correspondingly high upkeep.",
    "Nation Ruler": "Oversee a dynasty-wide domain dedicated to your household and practice.",
    "Pocket Dimension": "Retreat into a private dimension beyond the disturbances of the mortal world.",
    "Void Realm": "A secluded realm in the void offers a vast sanctuary for your household.",
    "Void Universe": "Make a boundless void heaven your dwelling, sustained by immense resources.",
    "Astral Realm": "A tranquil spiritual domain reflects the clarity of your inner world.",
    "Galactic Throne": "Reside upon a celestial throne overlooking the immortal heavens.",
    "Spaceship": "A palace carried by flight formations follows your journey between the heavens.",
    "Planet": "An entire spirit world shelters your household and cultivation grounds.",
    "Ringworld": "An immense heavenly ring holds gardens, residences and secluded sanctuaries.",
    "Stellar Neighborhood": "A constellation of spiritual domains forms your immortal residence.",
    "Galaxy": "A vast star domain supports the life and practice of your lineage.",
    "Supercluster": "An expanse of celestial domains sustains your household beyond mortal measure.",
    "Galaxy Filament": "A heavenly meridian links countless sanctuaries into a single dwelling.",
    "Observable Universe": "The boundless heavens become the home of your immortal lineage.",
    "Multiverse": "Your household spans the myriad worlds, supported by extraordinary upkeep.",
    "Quantum World": "Retreat to a primordial realm beneath the familiar laws of existence.",
    "Boötes Void": "In the great emptiness, your sanctuary stands beyond the noise of the heavens.",
    "Sapphire Charm": "A jade charm steadies your meridians and aids the study of spirit arts.",
    "Universe Fragment": "A fragment of a newborn heaven deepens your study of techniques.",
    "Multiverse Fragment": "A fragment of the myriad worlds brings harmony to your secluded life.",
    "Magic Eye": "The soul seal within your jade awakens, preserving understanding as its insight unfolds.",
    "Almighty Eye": "Your soul seal reaches clarity and preserves understanding throughout your life.",
    "Deal with the Devil": "An demonic covenant grants a continuing flow of Demonic Energy.",
    "Hell Portal": "A demonic gate opens, greatly strengthening passive Demonic Energy gain.",
    "Inferno": "A demonic furnace refines your inheritance and multiplies Demonic Energy gain.",
    "Mind Control": "Demonic communion deepens the flow of Demonic Energy.",
    "Galactic Emperor": "The Celestial Patriarch grants the insight to gather Dao Essence from distant heavens.",
    "Strange Magic": "A wandering sage shares hidden heavenly arts.",
    "The new Dark Matter": "Your soul jade opens a passage beyond the myriad worlds into the Heavenly Cycle.",
    "Squire":"Carry weapons for the Martial Hall and learn to guard the sect. Requires Qi Gathering I as well as Body Tempering.",
    "Footman":"Stand watch at the sect gates and escort disciples through contested lands.",
    "Veteran footman":"Lead experienced sentinels against threats to the sect's spirit veins.",
    "Centenary":"Coordinate patrol formations and protect the mountain paths.",
    "Knight":"Serve the Martial Hall through disciplined swordsmanship.",
    "Veteran Knight":"Guide younger sword disciples and safeguard the sect's expeditions.",
    "Holy Knight":"Wield a spirit-infused blade in defense of the sect's sacred grounds.",
    "Lieutenant General":"Command the Martial Hall and direct the sect's defenders.",
    "Student":"Study the scriptures of the Spirit Arts Hall. A modest stipend supports your training.",
    "Apprentice Mage":"Inscribe talismans under a master's guidance and assist the hall's adepts.",
    "Adept Mage":"Practice spirit arts and guide apprentices in meridian control.",
    "Master Wizard":"Design powerful formations to shelter the sect and strengthen its influence.",
    "Archmage":"Oversee the hall's spirit arts and pass your knowledge to promising disciples.",
    "Chronomancer":"Study the Dao of Time and maintain the sect's secluded training realms.",
    "Chairman":"Lead the Spirit Arts Hall and oversee its research into immortality.",
    "Imperator":"Unite the hall beneath your authority as its supreme patriarch.",
    "Corrupted":"Take the first steps along the Void Path and learn to endure its silence.",
    "Void Slave":"Serve the Void Path's elders while tempering your resolve.",
    "Void Fiend":"Refine void techniques and carry out the path's dangerous commissions.",
    "Abyss Anomaly":"Study the hidden principles that lie between the heavens.",
    "Void Wraith":"Cultivate a soul capable of enduring the space between worlds.",
    "Void Reaver":"Walk between realms and protect routes through the void.",
    "Void Lord":"Oversee a domain beyond the ordinary heavens.",
    "Abyss God":"Become an ancestor of the Void Path, guiding generations of its cultivators.",
    "Eternal Wanderer":"Travel the immortal realms in search of lost scriptures.",
    "Nova":"Forge stars into spiritual treasures for the Celestial Court.",
    "Sigma Proioxis":"Study and uphold the laws that bind the heavens together.",
    "Acallaris":"Guide the Celestial Court with wisdom from before the first heavenly cycle.",
    "One Above All":"Establish a lineage whose understanding reaches the origin of the Dao.",
    "Snow Crash":"Guard the threshold between successive heavenly cycles.",
    "Player One":"Preserve the order of reincarnation across the myriad worlds.",
    "Lost in the dark":"Seek the unrecorded paths beyond the wheel of reincarnation.",
    "Omega":"Stand at the origin of the heavenly cycle and guide its renewal.",
    "All Seeing Eye":"Perceive the needs of the Spirit Arts Hall and improve the income of its duties.",
    "The Devil inside you":"Your demonic covenant deepens, greatly improving Demonic Energy gain.",
    "God's Blessings":"Heaven favors your path. Your Inner Harmony grows and Demonic Talents endure their usual reset.",
    "Highway to hell":"Offer incense at the demonic altar to strengthen demonic power.",
    "Desintegration":"Refine the foundations of an inner world in this ancient cauldron.",
    "Tesseract":"A formation seal that binds the laws of an inner world.",
    "Hypersphere":"Enclose a heaven within a self-sustaining formation.",
    "Custom Galaxy":"A personal star realm whose scriptures nourish your understanding.",
    "Time is a flat circle":"Study the wheel of reincarnation and the patterns repeated across every life.",
    "Ruler of the Metaverse":"Master the passages linking one heavenly cycle to the next."
};

function initializeCultivationTheme() {
    const cachedText = new WeakMap();
    const cachedAttributes = new WeakMap();
    const excluded = "script,style,textarea,input,pre,code,[data-upstream-attribution]";
    function translateNode(node) {
        if (node.nodeType === Node.TEXT_NODE) {
            if (!node.parentElement || node.parentElement.closest(excluded)) return;
            const source = node.nodeValue;
            if (cachedText.get(node) === source) return;
            const translated = cultivationText(source);
            cachedText.set(node, translated);
            if (translated !== source) node.nodeValue = translated;
        } else if (node.nodeType === Node.ELEMENT_NODE && !node.matches(excluded)) {
            for (const attribute of ["title", "aria-label", "alt"]) {
                const source = node.getAttribute(attribute);
                if (source === null) continue;
                const previous = cachedAttributes.get(node) || {};
                if (previous[attribute] === source) continue;
                const translated = cultivationText(source);
                previous[attribute] = translated; cachedAttributes.set(node, previous);
                if (translated !== source) node.setAttribute(attribute, translated);
            }
            for (const child of node.childNodes) translateNode(child);
        }
    }
    translateNode(document.body);
    const observer = new MutationObserver(records => {
        for (const record of records) {
            if (record.type === "childList") for (const node of record.addedNodes) translateNode(node);
            else translateNode(record.target);
        }
    });
    observer.observe(document.body, {subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["title","aria-label","alt"]});
}
