/* Original ink-wash paintings; keys match the stable housing identifiers. */
const RESIDENCE_ART = Object.freeze({
    "Homeless": "img/residences/open-sky.webp",
    "Tent": "img/residences/travelers-tent.webp",
    "Wooden Hut": "img/residences/cultivators-hut.webp",
    "Cottage": "img/residences/mountain-cottage.webp",
    "House": "img/residences/courtyard-house.webp",
    "Large House": "img/residences/cultivation-estate.webp",
    "Small Palace": "img/residences/sect-pavilion.webp",
    "Grand Palace": "img/residences/sect-palace.webp",
    "Town Ruler": "img/residences/town-protector.webp",
    "City Ruler": "img/residences/city-guardian.webp",
    "Nation Ruler": "img/residences/dynasty-sovereign.webp",
    "Pocket Dimension": "img/residences/pocket-dimension.webp",
    "Void Realm": "img/residences/void-realm.webp",
    "Void Universe": "img/residences/void-universe.webp",
    "Astral Realm": "img/residences/astral-realm.webp",
    "Galactic Throne": "img/residences/celestial-throne.webp",
    "Spaceship": "img/residences/flying-palace.webp",
    "Planet": "img/residences/spirit-world.webp",
    "Ringworld": "img/residences/heavenly-ring.webp",
    "Stellar Neighborhood": "img/residences/constellation-domain.webp",
    "Galaxy": "img/residences/star-domain.webp",
    "Supercluster": "img/residences/celestial-expanse.webp",
    "Galaxy Filament": "img/residences/heavenly-meridian.webp",
    "Observable Universe": "img/residences/boundless-heavens.webp",
    "Multiverse": "img/residences/myriad-worlds.webp",
    "Quantum World": "img/residences/primordial-realm.webp",
    "Boötes Void": "img/residences/great-emptiness.webp"
});
