#!/usr/bin/env node
const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const {performance}=require('node:perf_hooks');const {createCultivationStages}=require('../js/realm-engine.js');
const root=path.resolve(__dirname,'..');const read=file=>JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''));
const json=value=>JSON.stringify(value,(_,v)=>typeof v==='number'&&!Number.isFinite(v)?String(v):v,2);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const csv=rows=>{const keys=Object.keys(rows[0]||{});return [keys.join(','),...rows.map(row=>keys.map(k=>'"'+String(typeof row[k]==='object'?JSON.stringify(row[k]):row[k]??'').replace(/"/g,'""')+'"').join(','))].join('\n')+'\n';};
function report(file,title,note,rows){const keys=Object.keys(rows[0]||{});fs.writeFileSync(file,`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(title)}</title><style>body{font:15px system-ui;margin:30px;background:#f2eddf;color:#343b30}h1{font:32px Georgia}p{max-width:90ch;line-height:1.6}input{padding:12px;width:300px;max-width:90%}.table{overflow:auto;max-height:75vh;margin-top:20px}table{border-collapse:collapse;white-space:nowrap}td,th{padding:10px 14px;text-align:left;border-bottom:1px solid #ccc4b2}th{position:sticky;top:0;background:#e1ddcc}tr:nth-child(even){background:#eae5d7}</style><h1>${escape(title)}</h1><p>${escape(note)}</p><label>Filter rows <input id="search" placeholder="Realm, time, housing…"></label><div class="table"><table><thead><tr>${keys.map(k=>'<th>'+escape(k)+'</th>').join('')}</tr></thead><tbody>${rows.map(row=>'<tr>'+keys.map(k=>'<td>'+escape(typeof row[k]==='object'?JSON.stringify(row[k]):row[k])+'</td>').join('')+'</tr>').join('')}</tbody></table></div><script>document.getElementById('search').addEventListener('input',e=>{for(const row of document.querySelectorAll('tbody tr'))row.hidden=!row.textContent.toLowerCase().includes(e.target.value.toLowerCase())})</script>`);}
async function main(){
 const args=process.argv.slice(2);const mode=args[0]&&!args[0].startsWith('--')?args.shift():'run';const options={};
 while(args.length){const k=args.shift();if(!k.startsWith('--'))throw Error('Expected --option');if(k==='--help'){options.help=true;continue;}const v=args.shift();if(v===undefined||v.startsWith('--'))throw Error('Missing value for '+k);options[k.slice(2)]=v;}
 if(options.help){console.log(`Balance tools\n  npm run balance -- run --hours 1000 --max-seconds 60\n  npm run balance -- run --preset endgame --hours 1 --policy none\n  npm run balance -- run --save path/to/checkpoint.json --hours 100\n  npm run balance:sweep -- --hours 1000 --harmony 1,1e6,1e12,1e30,1e60\nPacing: --normal-resets 2 --until-demonic true (simulation policy only; no game reset gate)\nOptions: --out DIR --tuning JSON --policy growth|early|none --min-life-seconds 300 --gain-ratio 0.5 --browser msedge|chromium|chrome\nRun uses exact 20 Hz ticks without rendering. Wall limits produce resumable checkpoints; they do not imply completion. Presets late/endgame are synthetic, not earned progress. Sweep is a fixed-harmony cultivation projection, not a whole-game playthrough.`);return;}
 if(!['run','sweep'].includes(mode))throw Error('Mode must be run or sweep');
 const number=(key,defaultValue,min=0)=>{const v=Number(options[key]??defaultValue);if(!Number.isFinite(v)||v<min)throw Error('Invalid --'+key);return v;};
 const hours=number('hours',mode==='run'?10:1000,0.000001);const maxSeconds=number('max-seconds',60,.1);
 const tuning=read(options.tuning?path.resolve(options.tuning):path.join(root,'content/cultivation-tuning.json'));
 const catalogue=read(path.join(root,'content/cultivation-realms.json'));const stages=createCultivationStages(catalogue,tuning);
 const out=path.resolve(options.out||path.join(root,'test-results','balance-'+mode+'-'+Date.now()));fs.mkdirSync(out,{recursive:true});
 const configuration={mode,hours,maxSeconds,tuning,catalogueStageCount:stages.length-1};fs.writeFileSync(path.join(out,'configuration.json'),json(configuration));
 if(mode==='sweep'){
  const harmonies=(options.harmony||'1,1e3,1e6,1e12,1e24,1e40,1e60').split(',').map(Number);if(harmonies.some(v=>!Number.isFinite(v)||v<=0))throw Error('Invalid --harmony');const speed=number('speed',4,Number.MIN_VALUE);const rows=[];
  Object.assign(configuration,{harmonies,speed});fs.writeFileSync(path.join(out,'configuration.json'),json(configuration));
  for(const harmony of harmonies){let days=0,life=1;for(let i=1;i<stages.length;i++){const previous=stages[i-1];const stageDays=previous.cost/(tuning.baseQiRate*harmony);days+=stageDays;life*=previous.lifespanFactor;rows.push({harmony,stage:i,realm:stages[i].name,qiCost:previous.cost,stageGameDays:stageDays,totalGameDays:days,totalPlayHours:days/speed/3600,withinBudget:days/speed/3600<=hours,lifespanMultiplier:life,skillXpPercent:i*tuning.skillXpPercentPerStage});}}
  fs.writeFileSync(path.join(out,'realms.csv'),csv(rows));fs.writeFileSync(path.join(out,'realms.json'),json(rows));report(path.join(out,'report.html'),'Cultivation threshold sweep',`All ${stages.length-1} stages. Fixed harmony and ${speed} game days per real second; immediate breakthroughs. Ignores aging, deaths, reincarnation, income and changing harmony. Budget: ${hours} play hours. This is a projection for tuning, not earned progress.`,rows);
  console.log(json({output:out,scenarios:harmonies.length,stages:stages.length-1,finalThreshold:stages.at(-2).cost}));return;
 }
 const preset=options.preset||'fresh';if(!['fresh','late','endgame'].includes(preset))throw Error('Invalid preset');if(options.save&&options.preset)throw Error('Choose --save or --preset');
 if(options['until-demonic']!==undefined&&!['true','false'].includes(options['until-demonic']))throw Error('--until-demonic must be true or false');
 if(!Number.isInteger(number('normal-resets',0)))throw Error('--normal-resets must be a whole number');
 const policy=options.policy||'growth';if(!['growth','early','none'].includes(policy))throw Error('Invalid policy');
 Object.assign(configuration,{preset:options.save?'imported-save':preset,policy,minLifeSeconds:number('min-life-seconds',300),gainRatio:number('gain-ratio',.5),normalResets:number('normal-resets',0),untilDemonic:options['until-demonic']==='true',sourceSave:options.save?path.resolve(options.save):null});
 fs.writeFileSync(path.join(out,'configuration.json'),json(configuration));
 let save=null;if(options.save){save=fs.readFileSync(path.resolve(options.save),'utf8').trim().replace(/^\uFEFF/,'');if(!save.startsWith('{'))save=Buffer.from(save,'base64').toString('utf8');const envelope=JSON.parse(save);envelope.state.save_date_time=0;save=JSON.stringify(envelope);}
 const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.txt':'text/plain'};
 const server=http.createServer((req,res)=>{try{const relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/, '')||'index.html';const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep))throw Error('path');const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'}).end(data)}catch{res.writeHead(404).end()}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
 try{
  let playwright;
  try{playwright=require('playwright');}catch(error){if(error.code!=='MODULE_NOT_FOUND')throw error;playwright=require(path.join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
  const {chromium}=playwright;const channel=options.browser||'msedge';browser=await chromium.launch({headless:true,...(channel==='chromium'?{}:{channel})});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/*',route=>{const request=route.request();if(['image','stylesheet','font'].includes(request.resourceType()))return route.abort();if(request.url().endsWith('/js/HackTimer.js'))return route.fulfill({body:'',contentType:'text/javascript'});if(request.url().endsWith('/js/realm-catalogue.js'))return route.fulfill({body:'const CULTIVATION_CATALOGUE='+JSON.stringify(catalogue)+';const CULTIVATION_TUNING='+JSON.stringify(tuning)+';',contentType:'text/javascript'});return route.continue()});
  await page.addInitScript(()=>{window.setInterval=()=>1;});await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>typeof gameloop!=='undefined');
  await page.addScriptTag({path:path.join(root,'tools/balance-browser.js')});await page.evaluate(options=>installBalanceSimulation(options),{save,preset,policy,minLifeSeconds:number('min-life-seconds',300),gainRatio:number('gain-ratio',.5),normalResets:number('normal-resets',0),untilDemonic:options['until-demonic']==='true'});
  const snapshots=[await page.evaluate(()=>balanceSimulation.snapshot())];const targetTicks=Math.ceil(hours*3600*20);if(!Number.isSafeInteger(targetTicks))throw Error('Requested duration is too large');const start=performance.now();let current=snapshots[0],lastLog=start;
  while(current.ticks<targetTicks&&!(options['until-demonic']==='true'&&current.firstDemonicSeconds!==null)&&!current.stopReason&&(performance.now()-start)/1000<maxSeconds){
   current=await page.evaluate(n=>balanceSimulation.runChunk(n),Math.min(20000,targetTicks-current.ticks));
   if(performance.now()-lastLog>5000){snapshots.push(current);console.log(`${(current.simulatedSeconds/3600).toFixed(3)} play hours | ${current.highestRealm} | ${current.housing}`);lastLog=performance.now();}
  }
  const result=await page.evaluate(()=>balanceSimulation.finish());snapshots.push(result.snapshot);const wallSeconds=(performance.now()-start)/1000;const status=options['until-demonic']==='true'&&current.firstDemonicSeconds!==null?'milestone-reached':result.snapshot.stopReason?'blocked':current.ticks>=targetTicks?'completed':'wall-time-limit';
  const summary={status,preset:save?'imported-save':preset,synthetic:save?null:preset!=='fresh',policy,requestedPlayHours:hours,simulatedPlayHours:current.simulatedSeconds/3600,wallSeconds,ticksPerSecond:current.ticks/wallSeconds,speedup:current.simulatedSeconds/wallSeconds,checkpointValid:!result.checkpointError,checkpointError:result.checkpointError,errors,...result.snapshot};
  fs.writeFileSync(path.join(out,'summary.json'),json(summary));fs.writeFileSync(path.join(out,'timeline.csv'),csv(snapshots));fs.writeFileSync(path.join(out,'events.json'),json(result.events));fs.writeFileSync(path.join(out,'checkpoint.json'),result.save);
  report(path.join(out,'report.html'),'Balance simulation',`${status}. ${summary.simulatedPlayHours.toFixed(4)} of ${hours} requested play hours in ${wallSeconds.toFixed(2)} seconds. ${summary.synthetic?'SYNTHETIC '+preset+' starting state, not earned progression.':'Starting state: '+summary.preset+'.'} Exact ticks; policy ${policy}. Challenges and skill-tree choices are not automatically optimized. Resume checkpoint.json for longer runs.`,snapshots);
  console.log(json({...summary,output:out}));if(errors.length)throw Error(errors.join('\n'));
 }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1});
