const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=file=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8').replace(/^\uFEFF/,''));
const catalogue=read('content/cultivation-realms.json');const tuning=read('content/cultivation-tuning.json');
const {createCultivationStages}=require('../js/realm-engine.js');
const stages=createCultivationStages(catalogue,tuning);
const output='/* Generated by tools/build-realms.cjs. Edit the JSON files in content/, then rebuild. */\nconst CULTIVATION_CATALOGUE = '+JSON.stringify(catalogue)+';\nconst CULTIVATION_TUNING = '+JSON.stringify(tuning)+';\n';
const destination=path.join(root,'js/realm-catalogue.js');
if(process.argv.includes('--check')){if(fs.readFileSync(destination,'utf8')!==output)throw Error('Realm bundle is stale; run npm run realms:build');}
else fs.writeFileSync(destination,output);
console.log(`${catalogue.realms.length} major realms / ${stages.length-1} minor stages; final Qi threshold ${stages.at(-2).cost.toExponential(3)}`);
